name: anything_vending_machine
description: 뭐든지 자판기
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ndef: "0.3.1"
  flutter_nfc_kit: "3.3.1"
  url_launcher: "6.1.11"
  prompt_dialog: ^1.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
